name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run docker build
        run: docker buildx build . -t ghcr.io/tweedegolf/debian:latest
