

name: Container Registry Cleanup

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * MON'

jobs:
  cleanup:
    - uses: "tweedegolf/cleanup-untagged-images-action@main"
      with:
        package: debian
