name: Docker

on:
  workflow_call:

jobs:
  docker:
    strategy:
      matrix:
        include:
          - version: trixie
            latest: false
            alt: testing
          - version: bookworm
            latest: true
            alt: stable
          - version: bullseye
            latest: false
            alt: oldstable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Build container image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
              DEBIAN_VERSION=${{matrix.version}}
          tags: |
              ghcr.io/tweedegolf/debian:${{matrix.version}}
              ghcr.io/tweedegolf/debian:${{matrix.alt}}
              ${{ matrix.latest && 'ghcr.io/tweedegolf/debian:latest' || '' }}
