name: Docker

on:
  workflow_call:

jobs:
  docker:
    strategy:
      matrix:
        include:
          - version: trixie
            latest: false
            alt: testing
          - version: bookworm
            latest: true
            alt: stable
          - version: bullseye
            latest: false
            alt: oldstable
    uses: "./.github/workflows/docker-image.yml"
    secrets: inherit
    with:
        push: ${{ github.ref == 'refs/heads/main' }}
        build-args: |
            DEBIAN_VERSION=${{matrix.version}}
        tags: |
            ghcr.io/tweedegolf/debian:${{matrix.version}}
            ghcr.io/tweedegolf/debian:${{matrix.alt}}
            ${{ matrix.latest && 'ghcr.io/tweedegolf/debian:latest' || '' }}
